### ISSUE TITLE
Usage of WebAssembly.Function.type

### ISSUE THREAD

**Issue by yurydelendik** [WebAssembly/js-promise-integration#25]
The test at https://github.com/WebAssembly/js-promise-integration/blob/48fbac8bae88c2b68d2f12996791561b69bb11f5/test/js-api/js-promise-integration/js-promise-integration.any.js#L5 use `WebAssebly.Function.type()` to determine the type of the function. I saw the same in the output produced by emscripten.

The js-types proposal at the https://github.com/WebAssembly/js-types/blob/main/proposals/js-types/Overview.md#addition-of-webassemblyfunction specifies it as a member of a Function object instance.

Which one is correct and is there a difference between two?

**Comment by thibaudmichaud** [comment]
This was all changed from the free-function style to the object-method style at some point: https://github.com/WebAssembly/js-types/issues/18
`Function` still seems to be missing from the spec text but I assume that it will match what the overview says, especially since it's consistent with the other objects (Table, Memory, Global).

In other words I believe the test is wrong, thanks for noticing! I'll update it.

**Comment by thibaudmichaud** [comment]
I integrated the change to the PR I was working on, which includes other general updates to the tests:
https://github.com/WebAssembly/js-promise-integration/pull/24/files
