### ISSUE TITLE
"Parallel execution" of two promising calls

### ISSUE THREAD

**Issue by yurydelendik** [WebAssembly/js-promise-integration#27]
This question inspired by the inaccuracy (?) in the tests at https://github.com/WebAssembly/js-promise-integration/blob/48fbac8bae88c2b68d2f12996791561b69bb11f5/test/js-api/js-promise-integration/js-promise-integration.any.js#L256-L262 -- looks like tests needs to be `promise_test` and wait on result.

The proposal discusses using global and a workaround for re-entrance issue. Let say multiple promising calls are made to the same instance without waiting on previous one to complete, and their suspending function may perform another promising calls. Is the suspender object tracking in the `$suspender` global as described in the proposal still valid in this case?

**Comment by fgmccabe** [comment]
The short answer is yes, but you need some care.
Using a global to store the suspender can be made to work with reentrancy.
What you do is take the global on the stack just before the call to the import. Then, restore the gobal on resume/reject.

This works because it is relying on the value stack as a temporary store.

**Comment by fgmccabe** [comment]
Resolved, please reopen if new concern arises
