### ISSUE TITLE
What is type of function returned from suspendOnReturnedPromise?

### ISSUE THREAD

**Issue by eqrion** [WebAssembly/js-promise-integration#3]
From a WebIDL snippet from the overview:
```
WebAssembly.Function suspendOnReturnedPromise(Function func);
```

Every `WebAssembly.Function` must have a functype. What is the type of this returned function?

The description of this function says:
```
The method suspender.suspendOnReturnedPromise(func) asserts that func is a Function object with a function type of the form [t*] -> [externref] and
```
As func is just a `Function` it may just be JS and not have a functype associated with it.

**Comment by fgmccabe** [comment]
Yes. Good question :)
It is possible we will have to change this. However, there is some intentionality here too:

1. It should not be possible to call the returned value from JavaScript. (This would violate one of our most basic constraints)
2. In V8 anyway, the final type of an imported function is determined by the signature of the import.
3. If we constrain the argument to be a WebAssembly.Function, that is 'unergonomic' since we need to allow JavaScript functions here and we don't actually need the type until  we instantiate.

It is not clear what the correct signature should be. Certainly, the easiest to implement is WebAssembly.Function -> WebAssembly.Function; but that is also unergonomic (we don't require types for other function imports)

It is a kind of side-effect of the wrapping operation.

**Comment by eqrion** [comment]
>     1. It should not be possible to call the returned value from JavaScript. (This would violate one of our most basic constraints)
> 

A WA.Function can still be called from JS. It acts the same as normal exported wasm functions.

In this specific case though, calling it from JS would always result in a trap as there would either be no active suspender or there would be JS frames between the active suspender and the current call.

>     2. In V8 anyway, the final type of an imported function is determined by the signature of the import.
> 

This is true for JS functions, as importing a JS function (semantically) creates a wrapper WA.Function with the same functype as the import. In the case of importing a WA.Function though, semantically only a signature check needs to be done.

>     3. If we constrain the argument to be a WebAssembly.Function, that is 'unergonomic' since we need to allow JavaScript functions here and we don't actually need the type until  we instantiate.
> 

Yes, definitely agreed that we should allow any function here. I would disagree though that we don't need the type until we instantiate. All WA.Function's have a functype, and that's the main reason they were added in js-types.

For example, this allows a WA.Function to be stored in a table of funcref which has no functype available.

It seems like there are two options here:
  1. Take a functype  as a parameter to `suspendOnReturnedPromise` just like the WA.Function constructor does
  2. Return a new type of function, possibly a `WA.ImportWrapperFunction` which has the semantics you want

**Comment by fgmccabe** [comment]
I think that option #1 corresponds to requiring the input to be a WebAssembly.Function.
option #2 is not something that is going to work well with existing tooling: it will require much more effort for not much gain.

**Comment by fgmccabe** [comment]
Requiring the argument to be a WebAssembly.Function has some downsides:
1. It is not required for normal imports
2. The type reflection proposal has not moved in recent times and we may wish to reach standard before they get there
3. We may not actually need it. Because of #1, V8 at least does not actually generate code for import wrappers until instantiation time.

OTOH, the value returned by suspendOnReturnedPromise is definitely an odd beast. If it is a Function, it is a special one that cannot be called by JavaScript code. If it is a WebAssembly.Function, it may still be called by JS and you have the additional complexity of requiring type information that is not needed elsewhere.

**Comment by eqrion** [comment]
> Requiring the argument to be a WebAssembly.Function has some downsides:
> 
>     1. It is not required for normal imports
> 

That works because a normal import has a `functype` that an import wrapper can use.

>     3. We may not actually need it. Because of [Refactored explainer to include 'static' version #1](https://github.com/WebAssembly/js-promise-integration/pull/1), V8 at least does not actually generate code for import wrappers until instantiation time.
> 

Interesting, what does V8 do if you try to put a WA.Function without a `functype` into a table?

> OTOH, the value returned by suspendOnReturnedPromise is definitely an odd beast. If it is a Function, it is a special one that cannot be called by JavaScript code. If it is a WebAssembly.Function, it may still be called by JS and you have the additional complexity of requiring type information that is not needed elsewhere.

I get the difficulty here, because it's definitely inconvenient to require a `functype` for each `suspendOnReturnedPromise`. 

But my understanding was that every WA.Function must have a `functype`, and that was the main purpose of adding the type. Without it, a WA.Function could not be used in tables where a `functype` is required for signature checks with call_indirect.

As I said above, the only other JS-API only design I can think of would be to introduce a new opaque WA.SuspendWrapper that is recognized by imports and doesn't require a `functype` as it's only usable with imports (which have a `functype`).

**Comment by fgmccabe** [comment]
Introducing a new opaque entity has knock-on effects on other proposals and tooling (e.g., ESM integration).
Our current thought is to stick with the super simple WebAssembly.Function only version of the API (draft in progress) and maybe elaborate it at a later stage.

**Comment by fgmccabe** [comment]
New API design (#30) resolves this question.
